const featureCategories = [
  { id: 'action', title: 'アクション', summary: '対象ユーザーや投稿に対する操作' },
  { id: 'post', title: '投稿', summary: 'ポスト、スレッド、投票、予約投稿' },
  { id: 'dm', title: 'DM', summary: 'DM送信と会話データ' },
  { id: 'follower', title: 'フォロワー', summary: 'フォロー整理と増減確認' },
  { id: 'collect', title: '収集', summary: 'プロフィール、投稿、検索結果の取得' },
  { id: 'analysis', title: '分析', summary: '反応、成長、相関の確認' },
  { id: 'monitor', title: '監視', summary: 'アカウントやキーワードの継続監視' },
  { id: 'automation', title: '自動化', summary: 'ワークフローとエージェント' },
  { id: 'data', title: 'データ', summary: 'エクスポート、移行、データセット' },
  { id: 'settings', title: '設定', summary: 'X連携、アカウント、環境設定' },
];

const statusLabels = {
  available: '利用可能',
  legacy: '既存画面',
  planned: '準備中',
};

const riskLabels = {
  low: '低',
  medium: '中',
  high: '高',
};

const dataFormatOptions = [
  { value: 'json', label: 'JSON' },
  { value: 'csv', label: 'CSV' },
];

const timelineFilterOptions = [
  { value: 'latest', label: '新着' },
  { value: 'top', label: '話題' },
  { value: 'people', label: 'ユーザー' },
  { value: 'photos', label: '画像' },
  { value: 'videos', label: '動画' },
];

const sentimentModeOptions = [
  { value: 'rules', label: '通常分析' },
  { value: 'llm', label: 'AI分析' },
];

const features = [
  {
    id: 'targetEngage',
    category: 'action',
    title: '対象ユーザー操作',
    summary: '1人のユーザーにLike、フォロー、DMをまとめて実行します。',
    operationType: 'targetEngage',
    queueType: 'targetEngage',
    consoleAction: 'targetEngage',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'targetUsername', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'likeCount', label: 'Likeする最新投稿数', type: 'number', min: 0, max: 10, default: 1 },
      { key: 'follow', label: 'フォローする', type: 'boolean', default: false },
      { key: 'dmMessage', label: 'DM本文', type: 'textarea', max: 1000, placeholder: 'DMを送る場合のみ入力' },
      { key: 'delaySeconds', label: '実行間隔', type: 'number', min: 2, max: 60, step: 0.5, default: 3, suffix: '秒' },
    ],
  },
  {
    id: 'sendDM',
    category: 'dm',
    title: 'DM送信',
    summary: '指定したユーザーに1通のDMを送ります。',
    operationType: 'sendDM',
    queueType: 'sendDM',
    consoleAction: 'sendDM',
    historyTypes: ['targetEngage', 'sendDM'],
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'usernames', label: '送信先リスト', type: 'usernameList', required: true, placeholder: '@username\n@username2', source: 'newFollowers' },
      { key: 'message', label: '本文', type: 'textarea', required: true, max: 1000 },
    ],
  },
  {
    id: 'likeTweet',
    category: 'action',
    title: '投稿にLike',
    summary: '指定した投稿にLikeします。',
    operationType: 'likeTweet',
    queueType: 'likeTweet',
    consoleAction: 'likeTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
    ],
  },
  {
    id: 'unlikeTweet',
    category: 'action',
    title: 'Like解除',
    summary: '指定した投稿のLikeを解除します。',
    operationType: 'unlikeTweet',
    queueType: 'unlikeTweet',
    consoleAction: 'unlikeTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
    ],
  },
  {
    id: 'replyToTweet',
    category: 'action',
    title: '返信',
    summary: '指定した投稿に返信します。',
    operationType: 'replyToTweet',
    queueType: 'replyToTweet',
    consoleAction: 'replyToTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
      { key: 'text', label: '返信文', type: 'textarea', required: true, max: 1000 },
    ],
  },
  {
    id: 'bookmarkTweet',
    category: 'action',
    title: 'ブックマーク',
    summary: '指定した投稿をブックマークします。',
    operationType: 'bookmarkTweet',
    queueType: 'bookmarkTweet',
    consoleAction: 'bookmarkTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
    ],
  },
  {
    id: 'autoLike',
    category: 'automation',
    title: '自動Like',
    summary: '検索語句または対象ユーザーの投稿にLikeします。',
    operationType: 'autoLike',
    queueType: 'autoLike',
    consoleAction: 'autoLike',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', placeholder: 'キーワードまたは #タグ' },
      { key: 'targetUsername', label: '対象ユーザー', type: 'username', placeholder: '@username' },
      { key: 'maxLikes', label: '最大Like数', type: 'number', min: 1, max: 50, default: 10 },
    ],
  },
  {
    id: 'followEngagers',
    category: 'action',
    title: '反応ユーザーフォロー',
    summary: '指定ポストに反応したユーザーを確認し、必要に応じてフォローします。',
    operationType: 'followEngagers',
    queueType: 'followEngagers',
    consoleAction: 'followEngagers',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: 'ポストURL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
      {
        key: 'engagementType',
        label: '反応種別',
        type: 'select',
        default: 'likes',
        options: [
          { value: 'likes', label: 'Like' },
          { value: 'retweets', label: 'リポスト' },
        ],
      },
      { key: 'maxFollows', label: 'フォロー上限', type: 'number', min: 1, max: 50, default: 10 },
      { key: 'likeLatestPost', label: 'フォロー後に最新ポストへLike', type: 'boolean', default: false },
    ],
  },
  {
    id: 'keywordFollow',
    category: 'action',
    title: 'キーワードフォロー',
    summary: '検索語句に合う投稿者を確認し、必要に応じてフォローします。',
    operationType: 'keywordFollow',
    queueType: 'keywordFollow',
    consoleAction: 'keywordFollow',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', required: true, placeholder: 'キーワードまたは #タグ' },
      { key: 'maxFollows', label: 'フォロー上限', type: 'number', min: 1, max: 50, default: 10 },
    ],
  },
  {
    id: 'autoComment',
    category: 'action',
    title: '自動コメント',
    summary: '検索結果または指定ユーザーの投稿にコメントします。',
    operationType: 'autoComment',
    queueType: 'autoComment',
    consoleAction: 'autoComment',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', placeholder: 'キーワードまたは #タグ' },
      { key: 'targetUsername', label: '対象ユーザー', type: 'username', placeholder: '@username' },
      { key: 'comment', label: 'コメント', type: 'textarea', required: true, max: 280 },
      { key: 'maxComments', label: 'コメント上限', type: 'number', min: 1, max: 20, default: 3 },
    ],
  },
  {
    id: 'detectUnfollowers',
    category: 'follower',
    title: 'フォローバック確認',
    summary: 'フォロー中とフォロワーを比較し、フォローバックがない相手を確認します。',
    operationType: 'detectUnfollowers',
    queueType: 'detectUnfollowers',
    consoleAction: 'detectUnfollowers',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '自分のXユーザー名', type: 'username', placeholder: '@your_account' },
      { key: 'maxUsers', label: '確認上限', type: 'number', min: 50, max: 5000, default: 1000 },
    ],
  },
  {
    id: 'unfollowNonFollowers',
    category: 'follower',
    title: 'フォローバックなし解除',
    summary: 'フォローバックがないアカウントを整理します。',
    operationType: 'unfollowNonFollowers',
    queueType: 'unfollowNonFollowers',
    consoleAction: 'unfollowNonFollowers',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'username', label: '自分のXユーザー名', type: 'username', placeholder: '空欄なら選択中のX連携' },
      { key: 'maxUsers', label: '確認上限', type: 'number', min: 50, max: 5000, default: 1000 },
      { key: 'limit', label: '解除上限', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'unfollowEveryone',
    category: 'follower',
    title: '全フォロー解除',
    summary: 'フォロー中のアカウントをまとめて解除します。',
    operationType: 'unfollowEveryone',
    queueType: 'unfollowEveryone',
    consoleAction: 'unfollowEveryone',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'username', label: '自分のXユーザー名', type: 'username', placeholder: '空欄なら選択中のX連携' },
      { key: 'maxUsers', label: '確認上限', type: 'number', min: 50, max: 5000, default: 500 },
      { key: 'limit', label: '解除上限', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'postTweet',
    category: 'post',
    title: 'ポスト投稿',
    summary: '1件のポストを投稿します。',
    operationType: 'postTweet',
    queueType: 'postTweet',
    consoleAction: 'postTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'text', label: '本文', type: 'textarea', required: true, max: 25000 },
      { key: 'replyTo', label: '返信先URL', type: 'url', placeholder: '返信にする場合のみ入力' },
    ],
  },
  {
    id: 'postThread',
    category: 'post',
    title: 'スレッド投稿',
    summary: '複数ポストをスレッドとして投稿します。',
    operationType: 'postThread',
    queueType: 'postThread',
    consoleAction: 'postThread',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'tweets', label: '本文', type: 'textarea', required: true, max: 25000, placeholder: '--- だけの行で区切る' },
    ],
  },
  {
    id: 'createPoll',
    category: 'post',
    title: '投票作成',
    summary: 'Xの投票ポストを作成します。',
    operationType: 'createPoll',
    queueType: 'createPoll',
    consoleAction: 'createPoll',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'question', label: '質問', type: 'textarea', required: true, max: 280 },
      { key: 'options', label: '選択肢', type: 'textarea', required: true, max: 1000, placeholder: '1行に1つ。2から4件' },
      { key: 'durationMinutes', label: '投票期間', type: 'number', min: 5, max: 10080, default: 1440, suffix: '分' },
    ],
  },
  {
    id: 'schedulePost',
    category: 'post',
    title: '予約投稿',
    summary: 'スケジュールタブから投稿予約を作成します。',
    operationType: 'postTweet',
    queueType: 'postTweet',
    consoleAction: 'postTweet',
    historyTypes: ['postTweet'],
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    page: '/calendar',
    fields: [
      { key: 'text', label: '本文', type: 'textarea', required: true, max: 25000 },
      { key: 'replyTo', label: '返信先URL', type: 'url', placeholder: '返信にする場合のみ入力' },
    ],
  },
  {
    id: 'deleteTweet',
    category: 'post',
    title: '投稿削除',
    summary: '指定した自分の投稿を削除します。',
    operationType: 'deleteTweet',
    queueType: 'deleteTweet',
    consoleAction: 'deleteTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
    ],
  },
  {
    id: 'conversations',
    category: 'dm',
    title: '会話一覧',
    summary: 'DMの会話一覧を取得します。',
    operationType: 'getConversations',
    queueType: 'getConversations',
    consoleAction: 'getConversations',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'exportDMs',
    category: 'dm',
    title: 'DMエクスポート',
    summary: 'DMデータを書き出します。',
    operationType: 'exportDMs',
    queueType: 'exportDMs',
    consoleAction: 'exportDMs',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    endpoint: '/api/messages/export',
    fields: [
      { key: 'conversationUrl', label: '会話URL', type: 'url', placeholder: '空欄の場合は会話一覧を取得' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 500, default: 100 },
      { key: 'format', label: '形式', type: 'select', default: 'json', options: dataFormatOptions },
    ],
  },
  {
    id: 'followerScan',
    category: 'follower',
    title: 'フォロワースキャン',
    summary: 'フォロワー増減を記録します。',
    operationType: 'followerScan',
    queueType: 'followerScan',
    consoleAction: 'followerScan',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    page: '/unfollowers',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', placeholder: '空欄なら選択中のX連携' },
      { key: 'limit', label: '取得上限', type: 'number', min: 50, max: 5000, default: 5000 },
    ],
  },
  {
    id: 'profile',
    category: 'collect',
    title: 'プロフィール取得',
    summary: '指定ユーザーのプロフィールを取得します。',
    operationType: 'getProfile',
    queueType: 'getProfile',
    consoleAction: 'getProfile',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
    ],
  },
  {
    id: 'followers',
    category: 'collect',
    title: 'フォロワー取得',
    summary: '指定ユーザーのフォロワー一覧を取得します。',
    operationType: 'getFollowers',
    queueType: 'getFollowers',
    consoleAction: 'getFollowers',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 5000, default: 100 },
    ],
  },
  {
    id: 'following',
    category: 'collect',
    title: 'フォロー中取得',
    summary: '指定ユーザーがフォローしているアカウントを取得します。',
    operationType: 'getFollowing',
    queueType: 'getFollowing',
    consoleAction: 'getFollowing',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 5000, default: 100 },
    ],
  },
  {
    id: 'tweets',
    category: 'collect',
    title: 'ツイート取得',
    summary: '指定ユーザーの投稿を取得します。',
    operationType: 'getTweets',
    queueType: 'getTweets',
    consoleAction: 'getTweets',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 500, default: 50 },
      { key: 'includeReplies', label: '返信も含める', type: 'boolean', default: false },
    ],
  },
  {
    id: 'searchTweets',
    category: 'collect',
    title: '検索',
    summary: 'キーワードで投稿を検索します。',
    operationType: 'searchTweets',
    queueType: 'searchTweets',
    consoleAction: 'searchTweets',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', required: true, placeholder: 'キーワードまたは #タグ' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 30 },
      { key: 'filter', label: '表示順', type: 'select', default: 'latest', options: timelineFilterOptions },
    ],
  },
  {
    id: 'hashtag',
    category: 'collect',
    title: 'ハッシュタグ検索',
    summary: 'ハッシュタグに合う投稿を取得します。',
    operationType: 'searchHashtag',
    queueType: 'searchHashtag',
    consoleAction: 'searchHashtag',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'hashtag', label: 'ハッシュタグ', type: 'text', required: true, placeholder: '#xactions' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 500, default: 50 },
      { key: 'filter', label: '表示順', type: 'select', default: 'latest', options: timelineFilterOptions },
    ],
  },
  {
    id: 'trends',
    category: 'collect',
    title: 'トレンド',
    summary: '現在のトレンドを取得します。',
    operationType: 'getTrends',
    queueType: 'getTrends',
    consoleAction: 'getTrends',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'category', label: 'カテゴリ', type: 'text', placeholder: '空欄でトレンド' },
    ],
  },
  {
    id: 'explore',
    category: 'collect',
    title: 'Explore',
    summary: 'Exploreタブの投稿を取得します。',
    operationType: 'getExploreFeed',
    queueType: 'getExploreFeed',
    consoleAction: 'getExploreFeed',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      {
        key: 'tab',
        label: 'タブ',
        type: 'select',
        default: 'foryou',
        options: [
          { value: 'foryou', label: 'おすすめ' },
          { value: 'trending', label: 'トレンド' },
          { value: 'news', label: 'ニュース' },
          { value: 'sports', label: 'スポーツ' },
          { value: 'entertainment', label: 'エンタメ' },
        ],
      },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 30 },
    ],
  },
  {
    id: 'bookmarks',
    category: 'collect',
    title: 'ブックマーク取得',
    summary: '保存済みブックマークを取得します。',
    operationType: 'getBookmarks',
    queueType: 'getBookmarks',
    consoleAction: 'getBookmarks',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 200, default: 50 },
      { key: 'format', label: '形式', type: 'select', default: 'json', options: dataFormatOptions },
    ],
  },
  {
    id: 'media',
    category: 'collect',
    title: 'メディア取得',
    summary: '指定ユーザーの画像や動画付き投稿を取得します。',
    operationType: 'getMedia',
    queueType: 'getMedia',
    consoleAction: 'getMedia',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 500, default: 50 },
      {
        key: 'type',
        label: '種類',
        type: 'select',
        default: 'all',
        options: [
          { value: 'all', label: 'すべて' },
          { value: 'images', label: '画像' },
          { value: 'videos', label: '動画' },
        ],
      },
    ],
  },
  {
    id: 'spaces',
    category: 'collect',
    title: 'Spaces',
    summary: 'ライブまたは予約中のSpacesを取得します。',
    operationType: 'getLiveSpaces',
    queueType: 'getLiveSpaces',
    consoleAction: 'getSpaces',
    historyTypes: ['getLiveSpaces', 'getScheduledSpaces', 'scrapeSpace'],
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    page: '/monitor',
    fields: [
      {
        key: 'mode',
        label: '取得対象',
        type: 'select',
        default: 'live',
        options: [
          { value: 'live', label: '配信中' },
          { value: 'scheduled', label: '予約中' },
          { value: 'scrape', label: 'URLから取得' },
        ],
      },
      { key: 'topic', label: '検索語', type: 'text', placeholder: '配信中を探す場合のみ任意' },
      { key: 'username', label: 'ユーザー', type: 'username', placeholder: '予約中を探す場合のみ任意' },
      { key: 'spaceUrl', label: 'Spaceリンク', type: 'url', placeholder: 'URLから取得する場合のみ入力' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'video',
    category: 'collect',
    title: '動画抽出',
    summary: '投稿URLから動画情報を抽出します。',
    operationType: 'extractVideo',
    queueType: 'extractVideo',
    consoleAction: 'extractVideo',
    authRequired: false,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    page: '/video',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
    ],
  },
  {
    id: 'thread',
    category: 'collect',
    title: 'スレッド展開',
    summary: '投稿URLからスレッドを読み取り、扱いやすい形式に整えます。',
    operationType: 'unrollThread',
    queueType: 'unrollThread',
    consoleAction: 'unrollThread',
    authRequired: false,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    page: '/thread',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
      {
        key: 'format',
        label: '出力形式',
        type: 'select',
        default: 'text',
        options: [
          { value: 'text', label: 'テキスト' },
          { value: 'markdown', label: 'Markdown' },
          { value: 'json', label: 'JSON' },
        ],
      },
      { key: 'maxTweets', label: '取得上限', type: 'number', min: 1, max: 100, default: 100 },
    ],
  },
  {
    id: 'analytics',
    category: 'analysis',
    title: '感情分析',
    summary: 'テキストのポジティブ/ネガティブ傾向を分析します。',
    operationType: 'analyzeSentiment',
    queueType: 'analyzeSentiment',
    consoleAction: 'analyzeSentiment',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    page: '/analytics-dashboard',
    fields: [
      { key: 'text', label: '分析するテキスト', type: 'textarea', required: true, max: 10000 },
      { key: 'mode', label: '分析方式', type: 'select', default: 'rules', options: sentimentModeOptions },
    ],
  },
  {
    id: 'engagementAnalysis',
    category: 'analysis',
    title: 'エンゲージメント分析',
    summary: '指定ユーザーの最近の投稿から反応傾向を分析します。',
    operationType: 'analyzeEngagement',
    queueType: 'analyzeEngagement',
    consoleAction: 'analyzeEngagement',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'tweetCount', label: '分析件数', type: 'number', min: 10, max: 200, default: 50 },
      { key: 'includeReplies', label: '返信も含める', type: 'boolean', default: false },
    ],
  },
  {
    id: 'growthHistory',
    category: 'analysis',
    title: '成長履歴',
    summary: '保存済みスナップショットからフォロワー推移を確認します。',
    operationType: 'growthHistory',
    queueType: 'growthHistory',
    consoleAction: 'growthHistory',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'days', label: '期間', type: 'number', min: 1, max: 365, default: 30, suffix: '日' },
      {
        key: 'interval',
        label: '集計単位',
        type: 'select',
        default: 'day',
        options: [
          { value: 'day', label: '日別' },
          { value: 'week', label: '週別' },
          { value: 'month', label: '月別' },
          { value: 'raw', label: '全データ' },
        ],
      },
    ],
  },
  {
    id: 'audienceOverlap',
    category: 'analysis',
    title: 'オーディエンス重複',
    summary: '2つのアカウントのフォロワー重複を調べます。',
    operationType: 'audienceOverlap',
    queueType: 'audienceOverlap',
    consoleAction: 'audienceOverlap',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'username1', label: '比較元', type: 'username', required: true, placeholder: '@account_a' },
      { key: 'username2', label: '比較先', type: 'username', required: true, placeholder: '@account_b' },
      { key: 'limit', label: '取得上限', type: 'number', min: 10, max: 5000, default: 500 },
    ],
  },
  {
    id: 'bestPostTime',
    category: 'analysis',
    title: '最適投稿時間',
    summary: '投稿ごとの反応から曜日と時間帯の傾向を見ます。',
    operationType: 'bestPostTime',
    queueType: 'bestPostTime',
    consoleAction: 'bestPostTime',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'tweetCount', label: '分析件数', type: 'number', min: 10, max: 200, default: 80 },
      { key: 'includeReplies', label: '返信も含める', type: 'boolean', default: false },
    ],
  },
  {
    id: 'analyticsReport',
    category: 'analysis',
    title: 'レポート',
    summary: 'プロフィール、反応、投稿時間、成長履歴をまとめます。',
    operationType: 'analyticsReport',
    queueType: 'analyticsReport',
    consoleAction: 'analyticsReport',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'tweetCount', label: '分析件数', type: 'number', min: 10, max: 200, default: 80 },
      { key: 'days', label: '成長履歴の期間', type: 'number', min: 1, max: 365, default: 30, suffix: '日' },
    ],
  },
  {
    id: 'priceCorrelation',
    category: 'analysis',
    title: '価格相関',
    summary: '投稿と価格の動きを比較します。',
    operationType: 'priceCorrelation',
    queueType: 'priceCorrelation',
    consoleAction: 'priceCorrelation',
    authRequired: false,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    page: '/price-correlation',
    fields: [
      { key: 'tweets', label: '投稿データJSON', type: 'textarea', required: true, max: 50000, placeholder: '[{"timestamp":1710000000000,"text":"..."}]' },
      { key: 'tokenId', label: '銘柄ID', type: 'text', placeholder: '例: bitcoin, solana' },
      { key: 'network', label: 'ネットワーク', type: 'text', placeholder: '例: solana, eth' },
      { key: 'poolAddress', label: 'プールアドレス', type: 'text' },
      { key: 'windows', label: '比較時間', type: 'text', placeholder: '1,24' },
    ],
  },
  {
    id: 'monitor',
    category: 'monitor',
    title: '監視',
    summary: 'アカウントやキーワードを1回監視し、スケジュールで継続確認できます。',
    operationType: 'monitorSnapshot',
    queueType: 'monitorSnapshot',
    consoleAction: 'monitorSnapshot',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    page: '/monitor',
    fields: [
      { key: 'target', label: '監視対象', type: 'text', required: true, placeholder: '@username またはキーワード' },
      {
        key: 'monitorType',
        label: '種類',
        type: 'select',
        default: 'mentions',
        options: [
          { value: 'mentions', label: 'メンション' },
          { value: 'keyword', label: 'キーワード' },
          { value: 'replies', label: '返信' },
        ],
      },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 20 },
      { key: 'sentimentMode', label: '感情分析', type: 'select', default: 'rules', options: sentimentModeOptions },
    ],
  },
  {
    id: 'workflows',
    category: 'automation',
    title: 'ワークフロー',
    summary: '複数の操作をつなげて自動化します。',
    operationType: 'runWorkflow',
    queueType: 'runWorkflow',
    consoleAction: 'runWorkflow',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    page: '/workflows',
    fields: [
      {
        key: 'action',
        label: '操作',
        type: 'select',
        default: 'list',
        options: [
          { value: 'list', label: '一覧' },
          { value: 'actions', label: '使える操作' },
          { value: 'run', label: '実行' },
          { value: 'runs', label: '実行履歴' },
        ],
      },
      { key: 'workflowId', label: 'ワークフローID', type: 'text' },
      { key: 'context', label: '追加データ', type: 'textarea', max: 20000, placeholder: '{"keyword":"xactions"}' },
      { key: 'limit', label: '履歴件数', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'agent',
    category: 'automation',
    title: 'エージェント',
    summary: '日次スケジュールに沿って自動運用します。',
    operationType: 'agentCommand',
    queueType: 'agentCommand',
    consoleAction: 'agentCommand',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    page: '/agent',
    fields: [
      {
        key: 'action',
        label: '操作',
        type: 'select',
        default: 'status',
        options: [
          { value: 'status', label: '状態' },
          { value: 'config', label: '設定' },
          { value: 'schedule', label: '予定' },
          { value: 'report', label: 'レポート' },
          { value: 'content', label: '投稿候補' },
          { value: 'score', label: 'スコア' },
          { value: 'start', label: '開始' },
          { value: 'stop', label: '停止' },
        ],
      },
      { key: 'text', label: 'スコア対象テキスト', type: 'textarea', max: 10000 },
      { key: 'days', label: '集計日数', type: 'number', min: 1, max: 90, default: 30 },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'datasets',
    category: 'data',
    title: 'データセット',
    summary: '取得したデータを管理します。',
    operationType: 'datasets',
    queueType: 'datasets',
    consoleAction: 'datasets',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    endpoint: '/api/datasets',
    fields: [
      {
        key: 'action',
        label: '操作',
        type: 'select',
        default: 'list',
        options: [
          { value: 'list', label: '一覧' },
          { value: 'get', label: '表示' },
          { value: 'export', label: '書き出し' },
        ],
      },
      { key: 'name', label: 'データセット名', type: 'text' },
      {
        key: 'format',
        label: '形式',
        type: 'select',
        default: 'json',
        options: [
          { value: 'json', label: 'JSON' },
          { value: 'csv', label: 'CSV' },
          { value: 'jsonl', label: 'JSONL' },
        ],
      },
      { key: 'offset', label: '開始位置', type: 'number', min: 0, max: 100000, default: 0 },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 1000, default: 100 },
    ],
  },
  {
    id: 'portability',
    category: 'data',
    title: 'エクスポート / 移行',
    summary: 'アカウントデータを書き出し、移行に備えます。',
    operationType: 'portability',
    queueType: 'portability',
    consoleAction: 'portability',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    endpoint: '/api/portability/export',
    fields: [
      {
        key: 'action',
        label: '操作',
        type: 'select',
        default: 'exports',
        options: [
          { value: 'exports', label: '保存済み一覧' },
          { value: 'export', label: '書き出し' },
          { value: 'migrate', label: '移行' },
          { value: 'diff', label: '差分比較' },
        ],
      },
      { key: 'username', label: '対象ユーザー', type: 'username', placeholder: '空欄なら選択中のX連携' },
      {
        key: 'formats',
        label: '形式',
        type: 'multiSelect',
        default: ['json', 'csv', 'md'],
        options: [
          { value: 'json', label: 'JSON' },
          { value: 'csv', label: 'CSV' },
          { value: 'md', label: 'Markdown' },
        ],
      },
      {
        key: 'only',
        label: '対象データ',
        type: 'multiSelect',
        default: [],
        options: [
          { value: 'profile', label: 'プロフィール' },
          { value: 'tweets', label: '投稿' },
          { value: 'followers', label: 'フォロワー' },
          { value: 'following', label: 'フォロー中' },
          { value: 'bookmarks', label: 'ブックマーク' },
        ],
      },
      { key: 'limit', label: '取得上限', type: 'number', min: 1, max: 5000, default: 500 },
      {
        key: 'platform',
        label: '移行先',
        type: 'select',
        default: 'bluesky',
        options: [
          { value: 'bluesky', label: 'Bluesky' },
          { value: 'mastodon', label: 'Mastodon' },
        ],
      },
      { key: 'exportDir', label: 'エクスポートディレクトリ', type: 'text' },
      { key: 'dirA', label: '比較元ディレクトリ', type: 'text' },
      { key: 'dirB', label: '比較先ディレクトリ', type: 'text' },
    ],
  },
  {
    id: 'accounts',
    category: 'settings',
    title: 'X連携',
    summary: '操作に使うアカウントを管理します。',
    operationType: 'accounts',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: false,
    supportsSchedule: false,
    riskLevel: 'medium',
    status: 'available',
    page: '/console',
    endpoint: '/api/accounts',
  },
];

const featureMap = new Map(features.map((feature) => [feature.id, feature]));

function getFeatureById(id) {
  return featureMap.get(id) || null;
}

function getFeatureHistoryTypes(feature) {
  if (!feature) return [];
  return feature.historyTypes || (feature.operationType ? [feature.operationType] : []);
}

function getPublicFeatureCatalog() {
  const categories = featureCategories.map((category) => {
    const categoryFeatures = features.filter((feature) => feature.category === category.id);
    return {
      ...category,
      total: categoryFeatures.length,
      available: categoryFeatures.filter((feature) => feature.status === 'available').length,
    };
  });

  return {
    categories,
    features: features.map((feature) => ({
      ...feature,
      statusLabel: statusLabels[feature.status] || feature.status,
      riskLabel: riskLabels[feature.riskLevel] || feature.riskLevel,
    })),
    statusLabels,
    riskLabels,
  };
}

export {
  featureCategories,
  features,
  getFeatureById,
  getFeatureHistoryTypes,
  getPublicFeatureCatalog,
};
