const featureCategories = [
  { id: 'action', title: 'アクション', summary: '対象ユーザーや投稿に対して実行する操作' },
  { id: 'post', title: '投稿', summary: 'ポスト、スレッド、予約投稿' },
  { id: 'dm', title: 'DM', summary: 'DM送信と会話データ' },
  { id: 'follower', title: 'フォロワー', summary: 'フォロー整理と増減確認' },
  { id: 'collect', title: '収集', summary: 'プロフィール、投稿、検索結果の取得' },
  { id: 'analysis', title: '分析', summary: '反応、成長、傾向の確認' },
  { id: 'monitor', title: '監視', summary: 'アカウントやキーワードの継続監視' },
  { id: 'automation', title: '自動化', summary: 'ワークフローとエージェント' },
  { id: 'data', title: 'データ', summary: 'エクスポート、移行、データセット' },
  { id: 'settings', title: '設定', summary: 'X連携、アカウント、環境設定' },
];

const statusLabels = {
  available: '利用可能',
  legacy: '既存画面',
  planned: '準備中',
};

const riskLabels = {
  low: '低',
  medium: '中',
  high: '高',
};

const features = [
  {
    id: 'targetEngage',
    category: 'action',
    title: '対象ユーザー操作',
    summary: '1人のユーザーに Like、Follow、DM をまとめて実行します。',
    operationType: 'targetEngage',
    queueType: 'targetEngage',
    consoleAction: 'targetEngage',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'targetUsername', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
      { key: 'likeCount', label: 'Likeする最新投稿数', type: 'number', min: 0, max: 10, default: 1 },
      { key: 'follow', label: 'フォローする', type: 'boolean', default: false },
      { key: 'dmMessage', label: 'DM本文', type: 'textarea', max: 1000, placeholder: 'DMを送る場合だけ入力' },
      { key: 'delayMs', label: '実行間隔', type: 'number', min: 2000, max: 60000, step: 500, default: 3000, suffix: 'ms' },
    ],
  },
  {
    id: 'sendDM',
    category: 'dm',
    title: 'DM送信',
    summary: '指定したユーザーに1通のDMを送ります。',
    operationType: 'targetEngage',
    queueType: 'targetEngage',
    consoleAction: 'sendDM',
    historyTypes: ['targetEngage', 'sendDM'],
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'username', label: '送信先', type: 'username', required: true, placeholder: '@username' },
      { key: 'message', label: '本文', type: 'textarea', required: true, max: 1000 },
      { key: 'delayMs', label: '実行間隔', type: 'number', min: 2000, max: 60000, step: 500, default: 3000, suffix: 'ms' },
    ],
  },
  {
    id: 'likeTweet',
    category: 'action',
    title: '投稿にLike',
    summary: '指定した投稿にLikeします。',
    operationType: 'likeTweet',
    queueType: 'likeTweet',
    consoleAction: 'likeTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
    ],
  },
  {
    id: 'unlikeTweet',
    category: 'action',
    title: 'Like解除',
    summary: '指定した投稿のLikeを解除します。',
    operationType: 'unlikeTweet',
    queueType: 'unlikeTweet',
    consoleAction: 'unlikeTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: '投稿URL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
    ],
  },
  {
    id: 'autoLike',
    category: 'automation',
    title: '自動Like',
    summary: '検索語句または対象ユーザーの投稿にLikeします。',
    operationType: 'autoLike',
    queueType: 'autoLike',
    consoleAction: 'autoLike',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', placeholder: 'keyword OR #hashtag' },
      { key: 'targetUsername', label: '対象ユーザー', type: 'username', placeholder: '@username' },
      { key: 'maxLikes', label: '最大Like数', type: 'number', min: 1, max: 50, default: 10 },
    ],
  },
  {
    id: 'followEngagers',
    category: 'action',
    title: '反応ユーザーフォロー',
    summary: '指定ポストに反応したユーザーを確認し、必要に応じてフォローします。',
    operationType: 'followEngagers',
    queueType: 'followEngagers',
    consoleAction: 'followEngagers',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'tweetUrl', label: 'ポストURL', type: 'url', required: true, placeholder: 'https://x.com/user/status/...' },
      { key: 'engagementType', label: '反応種別', type: 'text', placeholder: 'likes または retweets' },
      { key: 'maxFollows', label: 'フォロー上限', type: 'number', min: 1, max: 50, default: 10 },
    ],
  },
  {
    id: 'keywordFollow',
    category: 'action',
    title: 'キーワードフォロー',
    summary: '検索語句に合う投稿者を確認し、必要に応じてフォローします。',
    operationType: 'keywordFollow',
    queueType: 'keywordFollow',
    consoleAction: 'keywordFollow',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', required: true, placeholder: 'keyword OR #hashtag' },
      { key: 'maxFollows', label: 'フォロー上限', type: 'number', min: 1, max: 50, default: 10 },
    ],
  },
  {
    id: 'autoComment',
    category: 'action',
    title: '自動コメント',
    summary: '検索結果または指定ユーザーの投稿にコメントします。',
    operationType: 'autoComment',
    queueType: 'autoComment',
    consoleAction: 'autoComment',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', placeholder: 'keyword OR #hashtag' },
      { key: 'targetUsername', label: '対象ユーザー', type: 'username', placeholder: '@username' },
      { key: 'comment', label: 'コメント', type: 'textarea', required: true, max: 280 },
      { key: 'maxComments', label: 'コメント上限', type: 'number', min: 1, max: 20, default: 3 },
    ],
  },
  {
    id: 'detectUnfollowers',
    category: 'follower',
    title: 'フォロバなし確認',
    summary: 'フォロー中とフォロワーを比較し、フォロバなしを確認します。',
    operationType: 'detectUnfollowers',
    queueType: 'detectUnfollowers',
    consoleAction: 'detectUnfollowers',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '自分のXユーザー名', type: 'username', placeholder: '@your_account' },
      { key: 'maxUsers', label: '確認上限', type: 'number', min: 50, max: 5000, default: 1000 },
    ],
  },
  {
    id: 'unfollowNonFollowers',
    category: 'follower',
    title: 'フォロバなし解除',
    summary: 'フォロバがないアカウントを整理します。',
    operationType: 'unfollowNonFollowers',
    queueType: 'unfollowNonFollowers',
    consoleAction: 'unfollowNonFollowers',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'username', label: '自分のXユーザー名', type: 'username', placeholder: '空なら選択中のX連携' },
      { key: 'maxUsers', label: '確認上限', type: 'number', min: 50, max: 5000, default: 1000 },
      { key: 'limit', label: '解除上限', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'unfollowEveryone',
    category: 'follower',
    title: '全フォロー解除',
    summary: 'フォロー中のアカウントをまとめて解除します。',
    operationType: 'unfollowEveryone',
    queueType: 'unfollowEveryone',
    consoleAction: 'unfollowEveryone',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'username', label: '自分のXユーザー名', type: 'username', placeholder: '空なら選択中のX連携' },
      { key: 'maxUsers', label: '確認上限', type: 'number', min: 50, max: 5000, default: 500 },
      { key: 'limit', label: '解除上限', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'postTweet',
    category: 'post',
    title: 'ポスト投稿',
    summary: '1件のポストを投稿します。',
    operationType: 'postTweet',
    queueType: 'postTweet',
    consoleAction: 'postTweet',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'text', label: '本文', type: 'textarea', required: true, max: 25000 },
      { key: 'replyTo', label: '返信先URL', type: 'url', placeholder: '返信にする場合だけ入力' },
    ],
  },
  {
    id: 'postThread',
    category: 'post',
    title: 'スレッド投稿',
    summary: '複数ポストをスレッドとして投稿します。',
    operationType: 'postThread',
    queueType: 'postThread',
    consoleAction: 'postThread',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'available',
    fields: [
      { key: 'tweets', label: '本文', type: 'textarea', required: true, max: 25000, placeholder: '--- だけの行で区切る' },
    ],
  },
  {
    id: 'createPoll',
    category: 'post',
    title: '投票作成',
    summary: 'Xの投票ポストを作成します。',
    operationType: 'createPoll',
    queueType: 'createPoll',
    consoleAction: 'createPoll',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'available',
    fields: [
      { key: 'question', label: '質問', type: 'textarea', required: true, max: 280 },
      { key: 'options', label: '選択肢', type: 'textarea', required: true, max: 1000, placeholder: '1行に1つ、2から4件' },
      { key: 'durationMinutes', label: '投票期間', type: 'number', min: 5, max: 10080, default: 1440, suffix: '分' },
    ],
  },
  {
    id: 'schedulePost',
    category: 'post',
    title: '予約投稿',
    summary: 'Xの投稿予約を作成します。',
    operationType: 'schedulePost',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: false,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'legacy',
    page: '/calendar',
  },
  {
    id: 'conversations',
    category: 'dm',
    title: '会話一覧',
    summary: 'DMの会話一覧を取得します。',
    operationType: 'getConversations',
    queueType: 'getConversations',
    consoleAction: 'getConversations',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 20 },
    ],
  },
  {
    id: 'exportDMs',
    category: 'dm',
    title: 'DMエクスポート',
    summary: 'DMデータを書き出します。',
    operationType: 'exportDMs',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'legacy',
    endpoint: '/api/messages/export',
  },
  {
    id: 'followerScan',
    category: 'follower',
    title: 'フォロワースキャン',
    summary: 'フォロワー増減を記録します。',
    operationType: 'followerScan',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'legacy',
    page: '/unfollowers',
  },
  {
    id: 'profile',
    category: 'collect',
    title: 'プロフィール取得',
    summary: '指定ユーザーのプロフィールを取得します。',
    operationType: 'getProfile',
    queueType: 'getProfile',
    consoleAction: 'getProfile',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'username', label: '対象ユーザー', type: 'username', required: true, placeholder: '@username' },
    ],
  },
  {
    id: 'searchTweets',
    category: 'collect',
    title: '検索',
    summary: 'キーワードで投稿を検索します。',
    operationType: 'searchTweets',
    queueType: 'searchTweets',
    consoleAction: 'searchTweets',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'query', label: '検索語句', type: 'text', required: true, placeholder: 'keyword OR #hashtag' },
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 100, default: 30 },
      { key: 'filter', label: '表示順', type: 'text', placeholder: 'latest / top / people / photos / videos' },
    ],
  },
  {
    id: 'trends',
    category: 'collect',
    title: 'トレンド',
    summary: '現在のトレンドを取得します。',
    operationType: 'getTrends',
    queueType: 'getTrends',
    consoleAction: 'getTrends',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'category', label: 'カテゴリ', type: 'text', placeholder: '空欄でトレンド' },
    ],
  },
  {
    id: 'bookmarks',
    category: 'collect',
    title: 'ブックマーク取得',
    summary: '保存済みブックマークを取得します。',
    operationType: 'getBookmarks',
    queueType: 'getBookmarks',
    consoleAction: 'getBookmarks',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'available',
    fields: [
      { key: 'limit', label: '取得件数', type: 'number', min: 1, max: 200, default: 50 },
      { key: 'format', label: '形式', type: 'text', placeholder: 'json または csv' },
    ],
  },
  {
    id: 'spaces',
    category: 'collect',
    title: 'Spaces',
    summary: 'ライブまたは予定中のSpacesを取得します。',
    operationType: 'getLiveSpaces',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'legacy',
    page: '/monitor',
  },
  {
    id: 'video',
    category: 'collect',
    title: '動画抽出',
    summary: '投稿URLから動画を抽出します。',
    operationType: 'extractVideo',
    authRequired: false,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: false,
    riskLevel: 'low',
    status: 'legacy',
    page: '/video',
  },
  {
    id: 'thread',
    category: 'collect',
    title: 'スレッド展開',
    summary: 'スレッドを読みやすい形に展開します。',
    operationType: 'unrollThread',
    authRequired: false,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: false,
    riskLevel: 'low',
    status: 'legacy',
    page: '/thread',
  },
  {
    id: 'analytics',
    category: 'analysis',
    title: '分析ダッシュボード',
    summary: '反応や成長の傾向を確認します。',
    operationType: 'analytics',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'low',
    status: 'legacy',
    page: '/analytics-dashboard',
  },
  {
    id: 'priceCorrelation',
    category: 'analysis',
    title: '価格相関',
    summary: '投稿と価格の動きを比較します。',
    operationType: 'priceCorrelation',
    authRequired: false,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: false,
    riskLevel: 'low',
    status: 'legacy',
    page: '/price-correlation',
  },
  {
    id: 'monitor',
    category: 'monitor',
    title: '監視',
    summary: 'アカウントやキーワードの変化を追跡します。',
    operationType: 'monitor',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'legacy',
    page: '/monitor',
  },
  {
    id: 'workflows',
    category: 'automation',
    title: 'ワークフロー',
    summary: '複数の操作をつないで自動化します。',
    operationType: 'workflow',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'medium',
    status: 'legacy',
    page: '/workflows',
  },
  {
    id: 'agent',
    category: 'automation',
    title: 'エージェント',
    summary: '日次スケジュールに沿って自動運用します。',
    operationType: 'agent',
    authRequired: true,
    accountRequired: true,
    supportsDryRun: true,
    supportsSchedule: true,
    riskLevel: 'high',
    status: 'legacy',
    page: '/agent',
  },
  {
    id: 'datasets',
    category: 'data',
    title: 'データセット',
    summary: '取得したデータを管理します。',
    operationType: 'datasets',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: false,
    riskLevel: 'low',
    status: 'legacy',
    endpoint: '/api/datasets',
  },
  {
    id: 'portability',
    category: 'data',
    title: 'エクスポート / 移行',
    summary: 'アカウントデータを書き出し、移行に備えます。',
    operationType: 'portability',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: true,
    supportsSchedule: false,
    riskLevel: 'medium',
    status: 'legacy',
    endpoint: '/api/portability/export',
  },
  {
    id: 'accounts',
    category: 'settings',
    title: 'X連携',
    summary: '操作に使うXアカウントを管理します。',
    operationType: 'accounts',
    authRequired: true,
    accountRequired: false,
    supportsDryRun: false,
    supportsSchedule: false,
    riskLevel: 'medium',
    status: 'available',
    page: '/console',
    endpoint: '/api/accounts',
  },
];

const featureMap = new Map(features.map((feature) => [feature.id, feature]));

function getFeatureById(id) {
  return featureMap.get(id) || null;
}

function getFeatureHistoryTypes(feature) {
  if (!feature) return [];
  return feature.historyTypes || (feature.operationType ? [feature.operationType] : []);
}

function getPublicFeatureCatalog() {
  const categories = featureCategories.map((category) => {
    const categoryFeatures = features.filter((feature) => feature.category === category.id);
    return {
      ...category,
      total: categoryFeatures.length,
      available: categoryFeatures.filter((feature) => feature.status === 'available').length,
    };
  });

  return {
    categories,
    features: features.map((feature) => ({
      ...feature,
      statusLabel: statusLabels[feature.status] || feature.status,
      riskLabel: riskLabels[feature.riskLevel] || feature.riskLevel,
    })),
    statusLabels,
    riskLabels,
  };
}

export {
  featureCategories,
  features,
  getFeatureById,
  getFeatureHistoryTypes,
  getPublicFeatureCatalog,
};
